// OOPS IN JS:
/* PROTOTYPE:- JS HAVE A SPECIAL PROPERTY CALLED PROTOYPE THAT IS EITHER NULL OR REFERENCES ANOTHER OBJECT.
SETTING A PROTOTYPE: __proto__
CLASSES AND OBJECTS:-
A CLASS IS AN EXTENSIBLE PROGRAM CODE TEMPLATE FOR CREATING OBJECTS PROVIDING INITIAL VALUES FOR STATE AND IMPLEMEMNTATION OF BEHAVIOUR.

BASIC SYNTAX:
CLASS MYCLASS{
CLASS METHODS
CONSTRUCTOR(){}
METHOD1(){}
METHOD2(){}
}

THE CONSTRUCTOR METHOD:
CALLED AUTOMATICALLY BY NEW, SO WE CAN INITIALIZE THE OBJECT THERE.
CLASS INHERITANCE:- WAY FOR ONE CLASS TO EXTEND ANOTHER CLASS. THIS CAN BE DONE BY EXTEND KEYWORD.
THE EXTENDS KEYWORDS:- USED TO EXTENDS ANOTHER CLASS. 
SYNTAX: Class Child extends Parent
WE CAN CREATE A CLASS MONKEY THAT INHERITS FROM ANIMAL
*/
class Monkey extends Animal{
    hide(){
        alert('${this.name}hides!');
    }
}
let monkey=new Monkey("Monu")
monkey.run(7);
monkey.hide;