/* DOM: DOM TREE REFERS TO AN HTML PAGE WHERE ALL THE NODES ARE OBJECT. THERE ARE THREE TYPES OF NODES IN A DOM:-
1. TEXT NODES
2. ELEMENT NODES
3. COMMENT NODES
IN A HTML PAGE <HTML> IS ROOT AND <HEAD> AND <BODY> ARE ITS CHILDREN. 
A TEXT NODE IS ALWAYS A LEAF OF THE TREE.

WALKING THE DOM:
<HTML>
<HEAD>                    (DOCUMENT.HEAD)
<TITLE>HELLO</TITLE>      (DOCUMENT.BODY)-> PAGE BODY TAG
</HEAD>                   (DOCUMENT.DOCUMENTELEMENT)->PAGE HTML TAG
<BODY>

</BODY>
</HTML>
*/